export default defineAppConfig({
  ui: {
    select:{
        slots:{
            content:'rtl',
            base:'rtl'
        }
    },
    dropdownMenu:{
        slots:{
            group:'rtl'
        }
    },
    input:{
        slots:{
            base:'rtl'
        }
    },
    toast:{
        slots:{
            root:'rtl'
        }
    },
    table:{
        slots:{
            th:'rtl'
        }
    },
    slideover:{
        slots:{
            header:'rtl'
        }
    }
  }
})